# Generated by Django 6.1.1 on 2026-09-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account_app', '0001_initial'),
        ('txn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_reference_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_txns', to='bank_account_app.bankaccount')),
                ('txn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_txn', to='txn_app.txn')),
            ],
        ),
    ]
