# Generated by Django 6.1.1 on 2026-09-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_txn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktxn',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
