# Generated by Django 6.1 on 2026-08-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['description'], name='tasks_task_descrip_bb3738_idx'),
        ),
    ]
